routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Common Routes
Auth::routes();
Route::get('/', 'HomeController@index');


// Common Routes.
// Auction's routes that extends the CRUD resource need to be defined before the Resource routes
Route::get('auctions/{id}/bos', ['uses' => 'AuctionController@bos', 'as' => 'auction.bos', 'middleware' => ['auth']]);

// Frontend Routes
{
    Route::get('register/verify', 'Auth\RegisterController@showVerify');
    Route::post('register/verify', ['uses' => 'Auth\RegisterController@verify', 'as' => 'register.verify']);
    Route::resource('auctions', 'AuctionController',  ['except' => ['create', 'store', 'update', 'destroy', 'edit']]);
    Route::post('auctions', 'AuctionController@sort');
    Route::get('auctions/{id}', ['uses' => 'AuctionController@show', 'as' => 'auction.detail']);
    Route::post('auctions/{id}', 'AuctionController@createBid');
    Route::post('auctions/{id}/alert', 'AlertController@auctionAlert');
    Route::get('auctions/category/{id}', ['uses' => 'AuctionController@getCategory', 'as' => 'auction.category']);
    Route::post('auctions/category/{id}', 'AuctionController@sort');
    Route::post('auctions/category/{id}/alert', 'AlertController@categoryAlert');
    Route::resource('bids', 'BidController', ['except' => ['create', 'store', 'update', 'destroy']]);
    Route::resource('alerts', 'AlertController', ['except' => ['create', 'store', 'update', 'destroy']]);
    Route::get('profile', ['uses' => 'UserController@index', 'as' => 'user.profile']);
    Route::post('profile', 'UserController@update');
    Route::get('search', ['uses' => 'SearchController@auctions', 'as' => 'search.auctions']);
}

// Admin Routes
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']], function () {
    Route::get('/', function () {
        return redirect()->route('admin.dashboard');
    });
    Route::get('dashboard', ['uses' => 'AdminDashboardController@index', 'as' => 'admin.dashboard']);
    Route::get('settings', 'AdminSettingsController@index');
    Route::post('auctions/close', ['uses' => 'AuctionController@close', 'as' => 'auctions.close']);
    Route::resource('auctions', 'AuctionController', ['only' => ['show', 'create', 'store', 'update', 'destroy', 'edit']]);
    Route::resource('category', 'CategoryController', ['only' => ['store', 'destroy']]);
    Route::resource('businessunit', 'BusinessunitController', ['only' => ['store', 'destroy']]);
    Route::get('user', ['uses' => 'UserController@autocomplete']);
    Route::post('add/user', ['uses' => 'UserController@addAdmin', 'as' => 'admin.add']);
    Route::get('revoke/user/{id}', ['uses' => 'UserController@revokeAdmin', 'as' => 'admin.revoke']);
    Route::any('api/images/setFeatured', ['uses' => 'ImageController@setFeatured', 'as' => 'image.setFeatured']);
    Route::any('api/images/delete', ['uses' => 'ImageController@delete', 'as' => 'image.delete']);
    Route::get('auctions/{id}/email/{type}', ['uses' => 'AdminAuctionsEmailController@editEmail', 'as' => 'admin.editEmail']);
    Route::post('auctions/email/send', ['uses' => 'AdminAuctionsEmailController@sendEmail', 'as' => 'admin.sendEmail']);
    Route::get('bids/destroy/{id}', ['uses' => 'BidController@destroy', 'as' => 'bids.destroy']);
    Route::get('bids/winner/{id}', ['uses' => 'BidController@winner', 'as' => 'bids.winner']);
    Route::get('search', ['uses' => 'SearchController@auctions', 'as' => 'search.auctions_admins']);
});

// -- Special Route: read and return the image
Route::get('public/auction_images/{filename}', 'ImageController@show');
Route::get('auctions/category/public/auction_images/{filename}', 'ImageController@show');

resources/views/admin/activity_log.blade.php
<div class="row admin-auction-data">


  <div class="col-sm-12">

    <div class="jumbotron">

      <h3>Auction Activity</h3>
      <h5 class="small text-muted"><span class="text-danger">*</span>These fields are only visible to administrators</h5>

      <div cass="clearfix spacer"></div>

      <table class="table table-striped bids">

        @each('admin.activity_log_bid',$auction->bids()->orderBy('created_at', 'desc')->orderBy('amount', 'desc')->get(), 'bid')
        <tr class="admin">

          <td colspan="3">
            <strong>{{$auction->createdBy()->name}}</strong> published auction
          </td>
          <td>
            {{$auction->created_at->timezone('America/Chicago')->toFormattedDateString()}} {{$auction->created_at->timezone('America/Chicago')->format('g:i a T')}}
          </td>
        </tr>
      </table>

    </div>

  </div>
</div>

resources/views/admin/activity_log_bid.blade.php
<tr>
  <td>
    ${{$bid->amount}} by <strong>{{$bid->author()->name}}</strong> ({{$bid->author()->email}})
    @if ($bid->auction()->ended_at != null && $bid->winner == true)
      <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
    @endif
  </td>

  <td>
    @if ($bid->auction()->ended_at == null)
      <a href="#" class="pull-right" data-toggle="modal" data-target="#AuctionCloseModal">Make winner</a>
    @else
      <a href="{{URL::route('bids.winner', ['id' => $bid->id])}}" class="pull-right">Make winner</a>
    @endif
  </td>
  <td>
    <a href="{{URL::route('bids.destroy', ['id' => $bid->id])}}" class="text-danger deleteBidhref">Delete</a>
  </td>
  <td>
    {{$bid->created_at->timezone('America/Chicago')->toFormattedDateString()}} {{$bid->created_at->timezone('America/Chicago')->format('g:i a T')}}
  </td>
</tr>

resources/views/admin/auction-list-item.blade.php
<tr>
  <td data-order="{{$auction->id}}"><a href="{{ action('AuctionController@show', ['id' => $auction->id]) }}">{{$auction->id}}</a></td>
  <td>{{ $auction->getIR() }}</td>
  <td>
    <a href="{{ action('AuctionController@show', ['id' => $auction->id]) }}">
      <img class="img-responsive" src="/{{ isset($auction->featuredImage()->path) ? $auction->featuredImage()->path : 'assets/default.png' }}">
    </a>
  </td>
  <td>{{ $auction->winnerBid() != null ? $auction->winnerBid()->author()->email : ' - ' }}</td>
  <td>{{ $auction->item_name }}</td>
  <td>{{ $auction->category()->name }}</td>
  <td>{{ $auction->Businessunit()->name }}</td>
  <td>{{$auction->bids()->count()}}</td>
  <td>{{ isset($auction->ended_at) ? Carbon\Carbon::parse($auction->ended_at)->timezone('America/Chicago') : Carbon\Carbon::parse($auction->expires_at)->timezone('America/Chicago') }}</td>
  <td>${{ isset($auction->bids()->orderBy('amount', 'DESC')->first()->amount) ? $auction->bids()->orderBy('amount', 'DESC')->first()->amount : '0.00' }}</td>
</tr>

resources/views/admin/auction_close_modal.blade.php
<div class="modal fade modal-emails" id="AuctionCloseModal" tabindex="-1" role="dialog" aria-labelledby="Email Winner">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Close Auction</h4>
      </div>
      <div class="modal-body dark-bg">
        <div class="row">
          <div class="col-sm-12">
            {!! BootForm::open()->action(URL::route('auctions.close')) !!}
            {!! BootForm::hidden('id', 'id')->value($auction->id) !!}
            {!! BootForm::select('Select a winner', 'bid_id', $auction->selectWinnerOptions()) !!}
            {!! BootForm::submit('Confirm and Close Auction', 'btn btn-lg btn-block btn-danger btn-admin') !!}
            {!! BootForm::close() !!}
            <br/>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

resources/views/admin/auction_email_modal.blade.php
<div class="modal fade modal-emails" id="emailWinnerModal" tabindex="-1" role="dialog" aria-labelledby="Email Winner">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Email Auction Winner</h4>
      </div>
      <div class="modal-body dark-bg">
        <div class="list-group">
          <a href="{{ route('admin.editEmail', ['id' => $auction->id, 'type' => 'winner']) }}" class="list-group-item">
            <h4 class="list-group-item-heading">Congrats on your win!</h4>
            <p class="list-group-item-text">Includes payment and pick up info</p>
          </a>
          <a href="{{ route('admin.editEmail', ['id' => $auction->id, 'type' => 'pickup']) }}" class="list-group-item">
            <h4 class="list-group-item-heading">Please pick up your item</h4>
            <p class="list-group-item-text">Remind winner to pick up item</p>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

resources/views/admin/auctions_edit_images.blade.php
<div class="col-sm-4 image-button-group">
  {!! BootForm::radio('<img src="/'.$image->path.'" class=\'img-responsive\'>', '1')
                ->name('img_sel')
                ->addClass('image-feature')
                ->value($image->id)
                ->defaultCheckedState($image->featured)
                ->data('auc_id', $image->auction_id) !!}
  {!! BootForm::button('Delete')->addClass('image-delete')->data('img_id', $image->id)!!}
</div>

resources/views/admin/email_edit.blade.php
<div class="clearfix spacer"></div>
<h1>Review and edit email</h1>

<hr>
<div class="row">
  <div class="col-sm-10 col-md-8 col-lg-7">
    {!! BootForm::openHorizontal(['sm' => [4, 8]])->action(URL::route('admin.sendEmail')); !!}
    {!! BootForm::text('To:', 'mail_to_shown')->value($auction->winnerbid()->author()->name.' - '.$auction->winnerbid()->author()->email)->disable() !!}
    {!! BootForm::hidden('mail_to')->value($auction->winnerbid()->author()->email) !!}
    {!! BootForm::hidden('id')->value($auction->id) !!}
    {!! BootForm::text('Subject:', 'mail_subject')->value($mail_subject) !!}
    <hr>
    {!! BootForm::textarea('Message:', 'mail_body')->value($mail_body) !!}
    {!! BootForm::textarea('Signature:', 'mail_signature')->value($mail_signature) !!}
    <hr>
    <div class="spacer"></div>
    {!! BootForm::submit('Send email', 'btn btn-lg btn-block btn-success') !!}
    {!! BootForm::close() !!}
    <div class="spacer"></div>
  </div>
</div>

resources/views/admin/modal_settings_admin.blade.php
<div class="modal fade modal-category" id="createAdmin" tabindex="-1" role="dialog" aria-labelledby="Add Admin">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add Admin</h4>
      </div>
      <div class="modal-body dark-bg">
        <div class="row">
          {!! BootForm::openHorizontal(['sm' => [2, 10]])->action(URL::route('admin.add'))->id('addAdminForm') !!}
          <div class="col-sm-10 autocomplete-list">
          {!! BootForm::text('Name', 'name')->id('qu') !!}
          {!! BootForm::hidden('id', 'id')->id('h') !!}
          </div>
          <div class="col-sm-2">
          {!! BootForm::submit('Add', 'btn btn-success') !!}
          </div>
          {!! BootForm::close() !!}
        </div>
        <div id="addAdminAlert" class="row">
          <div class="col-sm-12">
            <div class="alert alert-warning alert-dismissible" role="alert" id="alertAddAdminLabel" style="margin: 20px 0 0;">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
              <strong>User does not exist or is already an Administrator.</strong>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

resources/views/admin/modal_settings_businessunit.blade.php
<div class="modal fade modal-businessunit" id="createBusinessUnit" tabindex="-1" role="dialog" aria-labelledby="Create Unit">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Create Business Unit</h4>
      </div>
      <div class="modal-body dark-bg">
        <div class="row">
          {!! BootForm::openHorizontal(['sm' => [2, 10]])->action(URL::route('businessunit.store'))->id('addBUForm'); !!}
          <div class="col-sm-10">
          {!! BootForm::text('Name', 'businessunit_name')->id('buNameField') !!}
          </div>
          <div class="col-sm-2">
          {!! BootForm::submit('Add', 'btn btn-success') !!}
          </div>
          {!! BootForm::close() !!}
        </div>
        <div id="addBUAlert" class="row">
          <div class="col-sm-12">
            <div class="alert alert-warning alert-dismissible" role="alert" id="alertAddBULabel" style="margin: 20px 0 0;">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
              <strong>Business Unit name cannot be empty.</strong>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

resources/views/admin/modal_settings_category.blade.php
<div class="modal fade modal-category" id="createCategory" tabindex="-1" role="dialog" aria-labelledby="Create Category">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Create Category</h4>
      </div>
      <div class="modal-body dark-bg">
        <div class="row">
          {!! BootForm::openHorizontal(['sm' => [2, 10]])->action(URL::route('category.store'))->id('addCategoryForm'); !!}
          <div class="col-sm-10">
          {!! BootForm::text('Name', 'category_name')->id('categoryNameField'); !!}
          </div>
          <div class="col-sm-2">
          {!! BootForm::submit('Add', 'btn btn-success') !!}
          </div>
          {!! BootForm::close() !!}
        </div>
        <div id="addCategoryAlert" class="row">
          <div class="col-sm-12">
            <div class="alert alert-warning alert-dismissible" role="alert" id="alertAddCategoryLabel" style="margin: 20px 0 0;">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
              <strong>Category name cannot be empty.</strong>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

resources/views/admin/navbar.blade.php
<nav class="navbar navbar-admin">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="collapsed navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-4" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{action('AdminDashboardController@index')}}">
        <img alt="Brand" src="/assets/logo.png" style="height: 40px;">
      </a>
      <h4 class="navbar-text">Bid Board Admin</h4>
    </div>
    @if (Auth::user() !=  null && Auth::user()->admin == true)
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-4">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{{ action('AdminSettingsController@index') }}">Settings</a></li>
          <li><a href="{{ action('AuctionController@index') }}">Browse</a></li>
          <li>
            <a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
              Logout
            </a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
              {{ csrf_field() }}
            </form>
          </li>
          <li>
            <button href="newitem.html" type="submit" class="btn btn-success navbar-btn" onclick="location.href='{{URL::route('auctions.create')}}'">New
              Auction
            </button>
          </li>
        </ul>
        {!! BootForm::open()->addClass('navbar-form navbar-right')->action(URL::route('search.auctions_admins'))->get(); !!}
        {!! BootForm::text('', 'q')->placeholder('Search bid board') !!}
        {!! BootForm::submit('Go', 'btn btn-default') !!}
        {!! BootForm::close() !!}
      </div>
    @endif
  </div>
</nav>

resources/views/admin/settings_categories.blade.php
<div class="col-sm-6">
  <div class="jumbotron">
    <h2>Categories</h2>
    <p>
      <a href="#" class="btn btn-success" data-toggle="modal" data-target="#createCategory">Add Category</a>
    </p>
    <table class="table table-striped bids">
      <tbody>
      @each('admin.settings_categories_item', $categories, 'category')
      </tbody>
    </table>
  </div>
</div>

resources/views/admin/settings_users.blade.php
<div class="col-sm-6">
  <div class="jumbotron">
    <h2>Admin Users</h2>
    <p>
      <a href="#" class="btn btn-success" data-toggle="modal" data-target="#createAdmin">Add Admin</a>
    </p>
    <table class="table table-striped bids">
      <tbody>
      @each('admin.settings_users_item', $users->where('admin', true), 'user')
      </tbody>
    </table>
  </div>
</div>

resources/views/admin/settings_users_item.blade.php
<tr>
  <td colspan="4">
    <a href="#">{{$user->name}}</a>
  </td>
  <td>
    Added {{$user->updated_at->toFormattedDateString()}}
  </td>
  <td>
    @if ($user->id == Auth::user()->id)
      <span class="pull-right">N/A</span>
    @else
      <a href="{{ route('admin.revoke', $user->id) }}" class="text-danger pull-right">Delete</a>
    @endif
  </td>
</tr>