routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Common Routes
Auth::routes();
Route::get('/', 'HomeController@index');


// Common Routes.
// Auction's routes that extends the CRUD resource need to be defined before the Resource routes
Route::get('auctions/{id}/bos', ['uses' => 'AuctionController@bos', 'as' => 'auction.bos', 'middleware' => ['auth']]);

// Frontend Routes
{
    Route::get('register/verify', 'Auth\RegisterController@showVerify');
    Route::post('register/verify', ['uses' => 'Auth\RegisterController@verify', 'as' => 'register.verify']);
    Route::resource('auctions', 'AuctionController',  ['except' => ['create', 'store', 'update', 'destroy', 'edit']]);
    Route::post('auctions', 'AuctionController@sort');
    Route::get('auctions/{id}', ['uses' => 'AuctionController@show', 'as' => 'auction.detail']);
    Route::post('auctions/{id}', 'AuctionController@createBid');
    Route::post('auctions/{id}/alert', 'AlertController@auctionAlert');
    Route::get('auctions/category/{id}', ['uses' => 'AuctionController@getCategory', 'as' => 'auction.category']);
    Route::post('auctions/category/{id}', 'AuctionController@sort');
    Route::post('auctions/category/{id}/alert', 'AlertController@categoryAlert');
    Route::resource('bids', 'BidController', ['except' => ['create', 'store', 'update', 'destroy']]);
    Route::resource('alerts', 'AlertController', ['except' => ['create', 'store', 'update', 'destroy']]);
    Route::get('profile', ['uses' => 'UserController@index', 'as' => 'user.profile']);
    Route::post('profile', 'UserController@update');
    Route::get('search', ['uses' => 'SearchController@auctions', 'as' => 'search.auctions']);
}

// Admin Routes
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']], function () {
    Route::get('/', function () {
        return redirect()->route('admin.dashboard');
    });
    Route::get('dashboard', ['uses' => 'AdminDashboardController@index', 'as' => 'admin.dashboard']);
    Route::get('settings', 'AdminSettingsController@index');
    Route::post('auctions/close', ['uses' => 'AuctionController@close', 'as' => 'auctions.close']);
    Route::resource('auctions', 'AuctionController', ['only' => ['show', 'create', 'store', 'update', 'destroy', 'edit']]);
    Route::resource('category', 'CategoryController', ['only' => ['store', 'destroy']]);
    Route::resource('businessunit', 'BusinessunitController', ['only' => ['store', 'destroy']]);
    Route::get('user', ['uses' => 'UserController@autocomplete']);
    Route::post('add/user', ['uses' => 'UserController@addAdmin', 'as' => 'admin.add']);
    Route::get('revoke/user/{id}', ['uses' => 'UserController@revokeAdmin', 'as' => 'admin.revoke']);
    Route::any('api/images/setFeatured', ['uses' => 'ImageController@setFeatured', 'as' => 'image.setFeatured']);
    Route::any('api/images/delete', ['uses' => 'ImageController@delete', 'as' => 'image.delete']);
    Route::get('auctions/{id}/email/{type}', ['uses' => 'AdminAuctionsEmailController@editEmail', 'as' => 'admin.editEmail']);
    Route::post('auctions/email/send', ['uses' => 'AdminAuctionsEmailController@sendEmail', 'as' => 'admin.sendEmail']);
    Route::get('bids/destroy/{id}', ['uses' => 'BidController@destroy', 'as' => 'bids.destroy']);
    Route::get('bids/winner/{id}', ['uses' => 'BidController@winner', 'as' => 'bids.winner']);
    Route::get('search', ['uses' => 'SearchController@auctions', 'as' => 'search.auctions_admins']);
});

// -- Special Route: read and return the image
Route::get('public/auction_images/{filename}', 'ImageController@show');
Route::get('auctions/category/public/auction_images/{filename}', 'ImageController@show');

resources/views/shared/auction_additional_images.blade.php
<div class="col-sm-2">
  <img class="img-responsive img-thumbs" src="/{{$image->path}}">
</div>

resources/views/shared/auction_bid_history.blade.php
<div class="row">
  <div class="col-xs-7">Someone else bid ${{ $other_bid->amount }}</div>
  <div class="col-xs-5">{{ $other_bid->created_at->timezone('America/Chicago')->format('n/j/y \a\t g:i:s a T') }}</div>
</div>

resources/views/shared/auction_view.blade.php
@if (Auth::user()->admin == 1 && $admin_flag)
  @include('admin.auction-tools')
@endif

<h1>{{$auction->item_name}} <small class="text-muted">@if (Auth::user()->admin == 1 && $admin_flag == null) (<a href="{{ action('AuctionController@show', ['id' => $auction->id]) }}">admin</a>) @endif</small></h1>

<div class="row">

  <div class="col-sm-5 col-md-6">
    <img class="img-responsive img-featured" src="/{{isset($auction->featuredImage()->path) ? $auction->featuredImage()->path : 'assets/default.png'}}">
    <div class="row">
      @if ($auction->images()->count()>1)
      @each('shared.auction_additional_images', $auction->images(), 'image')
      @endif
    </div>
  </div>

  <div class="col-sm-7 col-md-6">
    <h1 class="current-bid">
      ${{ $auction->currentBidAmount() }} <span class="small gray-light">current bid</span>
    </h1>
    <table class="table table-striped auction-details">
      <tr>
        <td colspan="2">
          <label>Description</label>
          <p>{{$auction->item_description}}</p>
        </td>
      </tr>
      <tr>
        <td>
          <label>Condition</label>
        </td>
        <td>
          <p>{{$auction->item_condition}}</p>
        </td>
      </tr>
      <tr>
        <td>
          <label>Time left</label>
        </td>
        <td>
          <p class="text-danger">{{$auction->timeRemain()}}</p>
        </td>
      </tr>
      @if ($auction->ended_at == null)
      <tr>
        <td>
          <label>Ends at</label>
        </td>
        <td>
          <p>{{Carbon\Carbon::parse($auction->expires_at)->timezone('America/Chicago')->format('n/j/y \a\t g:i:s a T')}}</p>
        </td>
      </tr>
      @endif
      @if ($auction->ended_at != null && $auction->winnerBid() != null && (Auth::user() == $auction->winnerBid()->author() || Auth::user()->admin == 1 && $admin_flag) )
      <tr>
        <td>
          <label>Bill Of Sale:</label>
        </td>
        <td>
          <a href="{{route('auction.bos', ['id' => $auction->id]) }}">Download</a>
        </td>
      </tr>
      @endif
    </table>
    @if (is_null($auction->ended_at) && !$admin_flag)
    <form class="bid clearfix img-rounded dark-bg" id="bidForm">
      <div class="fieldset disabled">
        <div class="row">
          <div class="col-sm-4">
            <label>Bid price</label>
            <div class="input-group">
              <div class="input-group-addon">$</div>
              <input type="number" id="init_price" class="form-control input-lg" min="{{ (isset($auction->highestbid()->amount) && $auction->highestbid()->amount >= $auction->min_bid) ? $auction->highestbid()->amount + 1 : $auction->min_bid }}"
                     placeholder="{{ (isset($auction->highestbid()->amount) && $auction->highestbid()->amount >= $auction->min_bid) ? $auction->highestbid()->amount + 1 : $auction->min_bid }}" required autofocus>
            </div>
            <div class="clearfix"></div>
            <label>Minimum bid: ${{ (isset($auction->highestbid()->amount) && $auction->highestbid()->amount >= $auction->min_bid) ? $auction->highestbid()->amount + 1 : $auction->min_bid }}</label>
          </div>
          <div class="col-sm-5 col-sm-offset-3">
            <label>&nbsp;</label><br>
            <input type="submit" value="Start Bid" class="btn btn-lg btn-block btn-success">
          </div>
        </div>
      </div>
    </form>

    <div class="spacer clearfix"></div>

    @if (Auth::user()->current_bid($auction->id))
    <div class="row">
      <div class="col-xs-6">
        <div class="dropdown dropdown-form">
          <button type="button" class="btn @if (is_null($watch)) btn-primary @else btn-success @endif"
                  id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            <span class="glyphicon glyphicon-ok @if (is_null($watch)) hidden @endif" aria-hidden="true"></span> Get Alerts
          </button>
          <form class="dropdown-menu" aria-labelledby="dropdownMenu1" method="POST" action="{{ Request::url() . '/alert' }}">
            {{ csrf_field() }}
            <div class="form-group">
              <label>
                <input type="checkbox" name="notify_email" @if (!is_null($watch) && $watch->notify_email) checked @endif>
                &nbsp;Get&nbsp;email&nbsp;notifications
              </label>
            </div>
            <div class="form-group">
              <label>
                <input type="checkbox" name="notify_phone" @if (!is_null($watch) && $watch->notify_phone) checked @endif
                @if (is_null(Auth::user()->phone)) disabled @endif>
                &nbsp;Get&nbsp;text&nbsp;notifications
              </label>
            </div>
            <div class="form-group">
              <input type="submit" class="btn btn-success" value="Confirm">
              <input type="button" class="btn btn-default" value="Cancel" onclick="$('#dropdownMenu1').dropdown('toggle');">
            </div>
          </form>
        </div>
      </div>
    </div>
    @endif

    @endif
  </div>
</div>

<hr>

<div class="row">
  <div class="col-sm-4">
    <div class="form-group clearfix">
      <label>Full Description</label>
      <p>{{$auction->item_description}}</p>
    </div>
    <div class="form-group clearfix">
      <label>IR Number</label>
      <p>{{ $auction->getIR() }}</p>
    </div>
    <div class="form-group clearfix">
      <label>Disclaimer</label>
      <p>Unit is in {{$auction->item_condition}} CONDITION. Buyer must be able to pick up item from site. All items sold on the employee bid board are sold "AS
        IS", "WHERE IS" and there are no implied or expressed warranties. Buyer bears all responsibilities. Investment Recovery Services reserves the right to discontinue
        or reject any bids at any time during this process.</p>
    </div>
  </div>
  <div class="col-sm-3">
    <div class="form-group clearfix">
      <label for="" class="control-label">Location</label>
      <p>{{ isset($auction->location) ? $auction->location : 'N/A' }}</p>
    </div>
    <div class="form-group clearfix">
      <label for="" class="ccontrol-label">Contact name</label>
      <p>{{$auction->contact_name}}</p>
    </div>
    <div class="form-group clearfix">
      <label for="" class="control-label">Contact phone</label>
      <p>{{$auction->contact_phone}}</p>
    </div>
    <div class="form-group clearfix">
      <label for="" class="control-label">Business unit</label>
      <p>{{$auction->businessunit()->name}}</p>
    </div>
  </div>
  @if (!$admin_flag)
  <div class="col-sm-5 bids">
    <label>Bids</label>
    <div class="row">
      @if (Auth::user()->current_bid($auction->id))
      <div class="col-xs-7"><strong class="text-success">Your bid ${{ Auth::user()->current_bid($auction->id)->amount }}</strong></div>
      <div class="col-xs-5"><strong class="text-success">{{ Auth::user()->current_bid($auction->id)->created_at->timezone('America/Chicago')->format('n/j/y \a\t g:i:s a T') }}</strong></div>
      @else
      <div class="col-xs-12"><strong class="text-danger">You did not start a bid on this auction yet!</strong></div>
      @endif
    </div>
    <!-- Someone's bid history else -->
    @each('shared.auction_bid_history', $others_bids, 'other_bid')
    <!-- End of Someone's bid history else -->
  </div>
  @endif
</div>

resources/views/shared/breadcrumbs.blade.php
<!-- BREADCRUMBS -->
<div class="container">
  <ol class="breadcrumb">
    <li><a href="{{ route('auctions.index') }}">Bid Board</a></li>
    <li><a href="{{ route('auction.category', $auction->category()->id ) }}">{{$auction->category()->name}}</a></li>
    <li class="active"><a href="{{ action('AuctionController@show', ['id' => $auction->id]) }}">{{$auction->item_name}}</a></li>
  </ol>
</div>

resources/views/shared/footer.blade.php
<hr>
<footer>
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
        <p>
          <a href="http://www.entergy.com/privacy_legal/privacy.aspx" target="_blank">Privacy Policy</a> |
          <a href="http://www.entergy.com/privacy_legal/legal.aspx" target="_blank">Terms &amp; Conditions</a>
          <br>&copy; 1998-{{ Carbon\Carbon::now()->format('Y') }} Entergy Corporation, All Rights Reserved.
          The Entergy name and logo are registered service marks of Entergy Corporation and may not be used without the express, written consent of Entergy
          Corporation.
        </p>
      </div>
    </div>
  </div>
</footer>

resources/views/shared/login.blade.php
<div class="panel panel-default">
  <div class="panel-heading"><strong>Log in to Entergy Bid Board</strong></div>
  <div class="panel-body">
    <form class="form-horizontal" role="form" method="POST" action="{{ route('login') }}">
      {{ csrf_field() }}

      <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
        <input id="email" type="email" class="form-control input-lg" name="email" value="{{ old('email') }}" required autofocus
               placeholder="Entergy email address...">

        @if ($errors->has('email'))
          <span class="help-block">
            <strong>{{ $errors->first('email') }}</strong>
          </span>
        @endif
      </div>

      <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
        <input id="password" type="password" class="form-control input-lg" name="password" required placeholder="Your password...">

        @if ($errors->has('password'))
          <span class="help-block">
            <strong>{{ $errors->first('password') }}</strong>
          </span>
        @endif
      </div>

      <div class="form-group">
        <p>
          <button type="submit" class="btn btn-primary btn-block btn-lg">
            Log In
          </button>
        </p>
      </div>
    </form>
  </div>
</div>

resources/views/shared/navbar.blade.php
<nav class="navbar navbar-default navbar-inverse" style="margin-bottom: 0;">
  <div class="container-fluid">
    <div class="navbar-header">
      @if (Auth::user())
      <button type="button" class="collapsed navbar-toggle" data-toggle="collapse"
              data-target="#bs-example-navbar-collapse-4" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      @endif
      <a class="navbar-brand" href="{{ route('auctions.index') }}">
        <img alt="Brand" src="{{ asset('assets/logo.png') }}" style="height: 40px;">
      </a>
    </div>

    @if (Auth::user())
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-4">
      <h4 class="navbar-text">Employee Bid Board</h4>
      <ul class="nav navbar-nav navbar-right">
        @if (Auth::check() && Auth::user()->admin == true)
        <li><a href="{{ route('admin.dashboard') }}">Admin</a></li>
        @endif
        <li><a href="{{ route('alerts.index') }}">Alerts</a></li>
        <li><a href="{{ route('bids.index') }}">My Bids</a></li>
        <li><a href="{{ route('user.profile') }}">My Info</a></li>
        <li>
          <a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
            Logout
          </a>

          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            {{ csrf_field() }}
          </form>
        </li>
      </ul>
      {!! BootForm::open()->addClass('navbar-form navbar-right')->action(URL::route('search.auctions'))->get(); !!}
      {!! BootForm::text('', 'q')->placeholder('Search bid board') !!}
      {!! BootForm::submit('Go', 'btn btn-default') !!}
      {!! BootForm::close() !!}
    </div>
    @endif

  </div>
</nav>

resources/views/shared/sort-menu.blade.php
<div class="pull-left" style="margin-right: 20px;">
  {!! BootForm::open()->post()->addClass('form-inline')->action(Request::url(), ['id' => 1]) !!}
    {!! BootForm::select('Sort by &nbsp;', 'sort-by')->options([
        'newest-date' => 'Date: newest first',
        'oldest-date' => 'Date: oldest first',
        'lowest-price' => 'Price: low to high',
        'highest-price' => 'Price: high to low'
      ])->select($sort_by)->onchange('this.form.submit()') !!}
  {!! BootForm::close() !!}
</div>

@if (isset($activeId))
<div class="pull-left">
  <div class="dropdown dropdown-form">
    <button type="button" class="btn @if (is_null($category_watch)) btn-primary @else btn-success @endif"
            id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      <span class="glyphicon glyphicon-ok @if (is_null($category_watch)) hidden @endif" aria-hidden="true"></span> Get Alerts
    </button>
    <form class="dropdown-menu" aria-labelledby="dropdownMenu1" method="POST" action="{{ Request::url() . '/alert' }}">
      {{ csrf_field() }}
      <div class="form-group">
        <label>
          <input type="checkbox" name="notify_email" @if (!is_null($category_watch) && $category_watch->notify_email) checked @endif>
          &nbsp;Get&nbsp;email&nbsp;notifications
        </label>
      </div>
      <div class="form-group">
        <label>
          <input type="checkbox" name="notify_phone" @if (!is_null($category_watch) && $category_watch->notify_phone) checked @endif
          @if (is_null(Auth::user()->phone)) disabled @endif>
          &nbsp;Get&nbsp;text&nbsp;notifications
        </label>
      </div>
      <div class="form-group">
        <input type="submit" class="btn btn-success" value="Confirm">
        <input type="button" class="btn btn-default" value="Cancel" onclick="$('#dropdownMenu1').dropdown('toggle');">
      </div>
    </form>
  </div>
</div>
@endif

<div class="clearfix"></div>